# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4090ad542f51b1c01fd6073a2a0d036504a9c2d88421888abc886f3d6838e47249b5b9cc65b5236611f457843088b82a0df1e8cf5c4eb71c963292016da84fad

test:
  secret_key_base: c102f9a8b374529294d4967d83055b7ca559b9eb5508d74bcf3c8a7644ca7f3bb996319cce15cffb34cc741d1d8e625b74d9b3310cf6b54044c43102e54d9fdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
